title: Dellean Santos | Software Engineer Resume
description: Software Engineer with 12+ years in tech. Worked with the top 10 BRL startups. Proficient in React, Node.js, AWS, and CI/CD. In love with teaching and learning.